CC = gcc
PARAMETROS = -g -O3 -ansi -Wall
LINK = -lm -lncurses
ARQUIVOS = main.c lib_spcinv.c lib_lista.c lib_graficos.c 

space: main.c lib_spcinv.c lib_spcinv.h lib_lista.c lib_lista.h lib_graficos.h lib_graficos.c
	clear
	$(CC) $(PARAMETROS) -o space $(ARQUIVOS) $(LINK)
